import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import  { getProjects } from './notion';

import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import { Chip, Container, Grid, Stack } from '@mui/material';
import { CardActionArea } from '@mui/material';
import ProjectCard from '@/components/cards/ProjectCard';
import TopNavigationBar from '@/components/navbar/NavBar';
import About from '@/components/about/About';
import { useRef } from 'react';
import Skills from '@/components/skills/Skills';
import Contact from '@/components/contact/Contact';

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps() {
  const projects = await getProjects();
  return {
    props: {
      projects,
    },
  };
}
interface Project {
  id: string;
  properties: [any];
}
interface Props {
  projects: Project[];
}

export default function Home({ projects }: Props) {
  const aboutRef = useRef();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <TopNavigationBar />
      <About />
      <ProjectCard projects={projects} />
      <Skills />
      <Contact />
    </>
  )
}



